# -*- coding: utf-8 -*-
"""2pythonclass.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Sm0DHDZOeVKKIYmAi3zWFKlIPXvl7dg3

# **INTRODUCTION TO PYTHON**

## Data Types
"""

type(True)

type("Hello World")

type(30)

type(10.0)

type([1,3,2,"Mary"])

type(["apples","grapes","mango"])

#this is a tuple
type((1,5,"mango"))

type({56,7,8})

type({"name":"mary","mark":70})

type({"students":["Mary", "John", "Liz"],"grades":[70,60,80]})

"""This is what we've learnt today

*   List item
*   List item

### String
"""

a="42"

print("Hello")

countryname="United Kingdom"
name ="Mercy"
print(countryname)
print(name)

#len checking length
len(name)

len(countryname)

#changing into a string
b=45
str(b)

float(b)

"""### String special characters"""

#\,\n,\t,\r,\b

print("I like \"python\"")

#creates new line
print("my name is Mercy \nI like Python")

#tab space
print("my name is Mercy\tI like Python")

#back space
print("my name is Mercy  \bI like Python")

#carriage return
print("my name is Mercy\rI like Python")

"""### Index and slicing"""

b="Country"

b[:5]
#same as
b[0:5]

b[-4]

b[::2]

print(b[::])
print(b[::2])

b[::-1]

"""### Concantenation"""

part1 = "United"
part2 = "Kingdom"
part1+ " "+part2

part1+40

"10"+"6"

"""### Format strings"""

c ="I am {} years {} "
b=50
c.format(b,"now")

string1="I {} be {} next year"
string1.format(50,"will")

weight= 5
product="apples"
string2= "I bought {b} kgs of {a} that cost me 20 pounds"
string2.format(a=weight,b=product)

#%d,%f,%s,%a
string3= "I bought %d kgs of %s that cost me %f pounds"%(5,"apples", 15.20)
print(string3)

string4="Hellp"
print(id(string4))

string4[4]=["o"]

string5="Hello"
print(id(string5))

string4="Hello"
print(id(string4))

"""### Operations"""

10*2

7-4

5+5

10/2

8%3

9%4

4**2

5**3

#PEMDAS
(5+3*6.6/12)**2

"""### Operators"""

5==7

5>7

5<7

5!=7

5>=7

5<=7

d=4
e=5
f=7

d>e and d<f

d>e or d<f

not(d>e)

print()

round??

string5.upper()

string5.count("l")

string5.replace("o","T").replace("l","s")

print()

price = float(input("Enter item price: "))